# Usar uma imagem base oficial do Python
FROM python:3.9-slim

# Definir o diretório de trabalho no container
WORKDIR /app

# Instalar dependências do sistema, se necessário (ex: cliente mysql)
RUN apt-get update && apt-get install -y default-mysql-client curl && rm -rf /var/lib/apt/lists/*

# Copiar os arquivos de requisitos primeiro para aproveitar o cache do Docker
COPY requirements.txt .

# Instalar as dependências do projeto e a biblioteca para testes de API
RUN pip install --no-cache-dir -r requirements.txt && pip install httpx

# Copiar o restante do código do projeto para o diretório de trabalho
COPY . .

# O comando a ser executado será definido no docker-compose.yml
CMD ["pytest", "backend/tests/integration"]
