services:
  caddy:
    image: caddy:latest
    container_name: sensorium_caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

  # --- APLICAÇÃO (FASTAPI) ---
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sensorium_app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 400M
    env_file:
      - .env.prod
    environment:
      PYTHONPATH: "/app"
      DISABLE_RATE_LIMITING: "true"
      EMAILS_FROM_NAME: "Sensorium UFRPE"
    volumes:
      - .:/app
      - ./templates:/app/templates
      - ./static:/app/static
    
    command: >
      sh -c "
        set -e
        echo 'Aguardando banco de dados...'
        sleep 5
        echo 'Inicializando banco de dados...'
        python backend/scripts/init_db.py
        echo 'Iniciando aplicação...'
        uvicorn backend.app.main:app --host 0.0.0.0 --port 8001 --proxy-headers --forwarded-allow-ips '*'
      "

  # --- BANCO DE DADOS ---
  mysql:
    image: mysql:8.0
    container_name: sensorium_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: "always"
    deploy:
      resources:
        limits:
          memory: 400M
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sensorium_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
  caddy_data:
  caddy_config: