[pytest]
markers =
    integration: mark a test as an integration test.

filterwarnings =
    ignore:.*'crypt' is deprecated.*:DeprecationWarning:passlib.utils.*
    ignore:.*ast.NameConstant is deprecated.*:DeprecationWarning:reportlab.lib.rl_safe_eval.*
    ignore:.*datetime.datetime.utcnow().*is deprecated.*:DeprecationWarning:sqlalchemy.sql.schema.*